### ISSUE TITLE
Checkboxes don't set boolean values

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/BGA-interface-projects#1]
When checking the "Keep Temporary Files" or "Bypass duplicate process check", the value does not get set /propagated.

**Comment by jmcmichael** [comment]
@susannasiebert the 'force' and 'keep_tmp_files' booleans appear to be working on the latest pvactools staging and bga-interface-projects develop branches. When you get a chance could you verify? I did some minor updates on unrelated issues - checking just now it looks like these are working.

**Comment by susannasiebert** [comment]
yes, it's working now for me. Resolving.
